In [2]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv("DSE3101_HDB_Resale_Price/backend/data_merged.csv")

In [3]:
df = df.drop(df.columns[0], axis=1)
df

,year,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,...,nearest_hawkers,dist_to_nearest_hawkers,hawkers_1km,nearest_primary_schools,dist_to_nearest_primary_schools,primary_schools_1km,nearest_hospital,dist_to_nearest_hospital,hospitals_1km,dist_cbd
0,1990,1,ANG MO KIO,3 ROOM,216,ANG MO KIO AVE 1,04 TO 06,73.0,NEW GENERATION,1976-01-01,...,226H ANG MO KIO STREET 22 KEBUN BARU FOOD CENT...,0.185551,4,20 ANG MO KIO AVENUE 3 ANG MO KIO PRIMARY SCHO...,0.405605,1,17 ANG MO KIO AVENUE 9 DBS ANG MO KIO COMMUNIT...,1.988128,0,8.784858
1,1990,1,ANG MO KIO,3 ROOM,211,ANG MO KIO AVE 3,01 TO 03,67.0,NEW GENERATION,1977-01-01,...,226H ANG MO KIO STREET 22 KEBUN BARU FOOD CENT...,0.280487,4,20 ANG MO KIO AVENUE 3 ANG MO KIO PRIMARY SCHO...,0.226983,3,17 ANG MO KIO AVENUE 9 DBS ANG MO KIO COMMUNIT...,1.656467,0,9.113857
2,1990,1,ANG MO KIO,3 ROOM,202,ANG MO KIO AVE 3,07 TO 09,67.0,NEW GENERATION,1977-01-01,...,724 ANG MO KIO AVENUE 6 MARKET & HAWKER CENTRE...,0.469385,4,20 ANG MO KIO AVENUE 3 ANG MO KIO PRIMARY SCHO...,0.552030,4,17 ANG MO KIO AVENUE 9 DBS ANG MO KIO COMMUNIT...,1.793124,0,8.998157
3,1990,1,ANG MO KIO,3 ROOM,235,ANG MO KIO AVE 3,10 TO 12,67.0,NEW GENERATION,1977-01-01,...,226D ANG MO KIO AVENUE 1 KEBUN BARU MARKET AND...,0.295063,2,20 ANG MO KIO AVENUE 3 ANG MO KIO PRIMARY SCHO...,0.446562,3,17 ANG MO KIO AVENUE 9 DBS ANG MO KIO COMMUNIT...,1.961956,0,8.943269
4,1990,1,ANG MO KIO,3 ROOM,235,ANG MO KIO AVE 3,04 TO 06,67.0,NEW GENERATION,1977-01-01,...,226D ANG MO KIO AVENUE 1 KEBUN BARU MARKET AND...,0.295063,2,20 ANG MO KIO AVENUE 3 ANG MO KIO PRIMARY SCHO...,0.446562,3,17 ANG MO KIO AVENUE 9 DBS ANG MO KIO COMMUNIT...,1.961956,0,8.943269
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
910092,2024,3,YISHUN,EXECUTIVE,791,YISHUN AVE 2,10 TO 12,146.0,Apartment,1975-06-11,...,628 ANG MO KIO AVENUE 4 ANG MO KIO 628 MARKET ...,4.470358,0,651 YISHUN RING ROAD COMMIT LEARNING SCHOOLHOU...,0.514113,4,2 YISHUN CENTRAL 2 YISHUN COMMUNITY HOSPITAL S...,0.546093,2,14.895912
910093,2024,3,YISHUN,EXECUTIVE,392,YISHUN AVE 6,07 TO 09,146.0,Maisonette,1975-06-12,...,628 ANG MO KIO AVENUE 4 ANG MO KIO 628 MARKET ...,5.396078,0,210 YISHUN AVENUE 6 NORTH VIEW PRIMARY SCHOOL ...,0.172412,2,90 YISHUN CENTRAL OCBC KHOO TECK PUAT HOSPITAL...,1.372029,0,15.670280
910094,2024,3,YISHUN,EXECUTIVE,326,YISHUN RING RD,10 TO 12,146.0,Maisonette,1975-06-12,...,628 ANG MO KIO AVENUE 4 ANG MO KIO 628 MARKET ...,5.409814,0,21 YISHUN AVENUE 11 MOE KINDERGARTEN @ HUAMIN ...,0.310632,4,90 YISHUN CENTRAL OCBC KHOO TECK PUAT HOSPITAL...,0.811998,2,15.796888
910095,2024,3,YISHUN,EXECUTIVE,360,YISHUN RING RD,04 TO 06,146.0,Maisonette,1975-06-12,...,628 ANG MO KIO AVENUE 4 ANG MO KIO 628 MARKET ...,5.234521,0,21 YISHUN AVENUE 11 MOE KINDERGARTEN @ HUAMIN ...,0.183997,3,90 YISHUN CENTRAL OCBC KHOO TECK PUAT HOSPITAL...,0.971766,1,15.575528
910096,2024,3,YISHUN,EXECUTIVE,606,YISHUN ST 61,07 TO 09,142.0,Apartment,1975-06-11,...,628 ANG MO KIO AVENUE 4 ANG MO KIO 628 MARKET ...,4.516895,0,15 YISHUN AVENUE 4 NASCANS NORTHLAND STUDENT C...,0.497976,4,2 YISHUN CENTRAL 2 YISHUN COMMUNITY HOSPITAL S...,0.289731,2,14.947349

In [4]:
# init setup
from pycaret.regression import *
clf1 = setup(data = df,  target = 'resale_price')

# compare models
best = compare_models()

Initiated  . . . . . . . . . . . . . . . . . .               09:07:37
Status     . . . . . . . . . . . . . . . . . .       Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Extra Trees Regressor

Processing:   0%|          | 0/77 [00:00<?, ?it/s]